// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: proto/market.proto

package market

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Exchange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exchange) Reset() {
	*x = Exchange{}
	mi := &file_proto_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exchange) ProtoMessage() {}

func (x *Exchange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exchange.ProtoReflect.Descriptor instead.
func (*Exchange) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{0}
}

func (x *Exchange) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TokenSymbol struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseAsset     string                 `protobuf:"bytes,1,opt,name=base_asset,json=baseAsset,proto3" json:"base_asset,omitempty"`
	QouteAsset    string                 `protobuf:"bytes,2,opt,name=qoute_asset,json=qouteAsset,proto3" json:"qoute_asset,omitempty"`
	Exchanges     []*Exchange            `protobuf:"bytes,3,rep,name=exchanges,proto3" json:"exchanges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenSymbol) Reset() {
	*x = TokenSymbol{}
	mi := &file_proto_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenSymbol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenSymbol) ProtoMessage() {}

func (x *TokenSymbol) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenSymbol.ProtoReflect.Descriptor instead.
func (*TokenSymbol) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{1}
}

func (x *TokenSymbol) GetBaseAsset() string {
	if x != nil {
		return x.BaseAsset
	}
	return ""
}

func (x *TokenSymbol) GetQouteAsset() string {
	if x != nil {
		return x.QouteAsset
	}
	return ""
}

func (x *TokenSymbol) GetExchanges() []*Exchange {
	if x != nil {
		return x.Exchanges
	}
	return nil
}

type MarketPrice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseAsset     string                 `protobuf:"bytes,1,opt,name=base_asset,json=baseAsset,proto3" json:"base_asset,omitempty"`    // 基础资产
	QouteAsset    string                 `protobuf:"bytes,2,opt,name=qoute_asset,json=qouteAsset,proto3" json:"qoute_asset,omitempty"` // 报价资产
	MarketPrice   string                 `protobuf:"bytes,3,opt,name=market_price,json=marketPrice,proto3" json:"market_price,omitempty"`
	SellPrice     string                 `protobuf:"bytes,4,opt,name=sell_price,json=sellPrice,proto3" json:"sell_price,omitempty"`
	BuyPrice      string                 `protobuf:"bytes,5,opt,name=buy_price,json=buyPrice,proto3" json:"buy_price,omitempty"`
	Rate          string                 `protobuf:"bytes,6,opt,name=rate,proto3" json:"rate,omitempty"` // 涨跌幅
	Hours24Trade  string                 `protobuf:"bytes,7,opt,name=hours24_trade,json=hours24Trade,proto3" json:"hours24_trade,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketPrice) Reset() {
	*x = MarketPrice{}
	mi := &file_proto_market_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketPrice) ProtoMessage() {}

func (x *MarketPrice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketPrice.ProtoReflect.Descriptor instead.
func (*MarketPrice) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{2}
}

func (x *MarketPrice) GetBaseAsset() string {
	if x != nil {
		return x.BaseAsset
	}
	return ""
}

func (x *MarketPrice) GetQouteAsset() string {
	if x != nil {
		return x.QouteAsset
	}
	return ""
}

func (x *MarketPrice) GetMarketPrice() string {
	if x != nil {
		return x.MarketPrice
	}
	return ""
}

func (x *MarketPrice) GetSellPrice() string {
	if x != nil {
		return x.SellPrice
	}
	return ""
}

func (x *MarketPrice) GetBuyPrice() string {
	if x != nil {
		return x.BuyPrice
	}
	return ""
}

func (x *MarketPrice) GetRate() string {
	if x != nil {
		return x.Rate
	}
	return ""
}

func (x *MarketPrice) GetHours24Trade() string {
	if x != nil {
		return x.Hours24Trade
	}
	return ""
}

type SupportSymbolListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	BaseAsset     string                 `protobuf:"bytes,2,opt,name=base_asset,json=baseAsset,proto3" json:"base_asset,omitempty"`
	QouteAsset    string                 `protobuf:"bytes,3,opt,name=qoute_asset,json=qouteAsset,proto3" json:"qoute_asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportSymbolListReq) Reset() {
	*x = SupportSymbolListReq{}
	mi := &file_proto_market_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportSymbolListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportSymbolListReq) ProtoMessage() {}

func (x *SupportSymbolListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportSymbolListReq.ProtoReflect.Descriptor instead.
func (*SupportSymbolListReq) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{3}
}

func (x *SupportSymbolListReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SupportSymbolListReq) GetBaseAsset() string {
	if x != nil {
		return x.BaseAsset
	}
	return ""
}

func (x *SupportSymbolListReq) GetQouteAsset() string {
	if x != nil {
		return x.QouteAsset
	}
	return ""
}

type SupportSymbolListRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint64                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	TokenSymbols  []*TokenSymbol         `protobuf:"bytes,3,rep,name=tokenSymbols,proto3" json:"tokenSymbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportSymbolListRep) Reset() {
	*x = SupportSymbolListRep{}
	mi := &file_proto_market_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportSymbolListRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportSymbolListRep) ProtoMessage() {}

func (x *SupportSymbolListRep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportSymbolListRep.ProtoReflect.Descriptor instead.
func (*SupportSymbolListRep) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{4}
}

func (x *SupportSymbolListRep) GetCode() uint64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SupportSymbolListRep) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SupportSymbolListRep) GetTokenSymbols() []*TokenSymbol {
	if x != nil {
		return x.TokenSymbols
	}
	return nil
}

type MarketPriceListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	BaseAsset     string                 `protobuf:"bytes,2,opt,name=base_asset,json=baseAsset,proto3" json:"base_asset,omitempty"`
	QouteAsset    string                 `protobuf:"bytes,3,opt,name=qoute_asset,json=qouteAsset,proto3" json:"qoute_asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketPriceListReq) Reset() {
	*x = MarketPriceListReq{}
	mi := &file_proto_market_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketPriceListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketPriceListReq) ProtoMessage() {}

func (x *MarketPriceListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketPriceListReq.ProtoReflect.Descriptor instead.
func (*MarketPriceListReq) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{5}
}

func (x *MarketPriceListReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *MarketPriceListReq) GetBaseAsset() string {
	if x != nil {
		return x.BaseAsset
	}
	return ""
}

func (x *MarketPriceListReq) GetQouteAsset() string {
	if x != nil {
		return x.QouteAsset
	}
	return ""
}

type MarketPriceListRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint64                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	MarketPrices  []*MarketPrice         `protobuf:"bytes,3,rep,name=marketPrices,proto3" json:"marketPrices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketPriceListRep) Reset() {
	*x = MarketPriceListRep{}
	mi := &file_proto_market_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketPriceListRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketPriceListRep) ProtoMessage() {}

func (x *MarketPriceListRep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_market_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketPriceListRep.ProtoReflect.Descriptor instead.
func (*MarketPriceListRep) Descriptor() ([]byte, []int) {
	return file_proto_market_proto_rawDescGZIP(), []int{6}
}

func (x *MarketPriceListRep) GetCode() uint64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MarketPriceListRep) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *MarketPriceListRep) GetMarketPrices() []*MarketPrice {
	if x != nil {
		return x.MarketPrices
	}
	return nil
}

var File_proto_market_proto protoreflect.FileDescriptor

const file_proto_market_proto_rawDesc = "" +
	"\n" +
	"\x12proto/market.proto\"\x1e\n" +
	"\bExchange\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"v\n" +
	"\vTokenSymbol\x12\x1d\n" +
	"\n" +
	"base_asset\x18\x01 \x01(\tR\tbaseAsset\x12\x1f\n" +
	"\vqoute_asset\x18\x02 \x01(\tR\n" +
	"qouteAsset\x12'\n" +
	"\texchanges\x18\x03 \x03(\v2\t.ExchangeR\texchanges\"\xe5\x01\n" +
	"\vMarketPrice\x12\x1d\n" +
	"\n" +
	"base_asset\x18\x01 \x01(\tR\tbaseAsset\x12\x1f\n" +
	"\vqoute_asset\x18\x02 \x01(\tR\n" +
	"qouteAsset\x12!\n" +
	"\fmarket_price\x18\x03 \x01(\tR\vmarketPrice\x12\x1d\n" +
	"\n" +
	"sell_price\x18\x04 \x01(\tR\tsellPrice\x12\x1b\n" +
	"\tbuy_price\x18\x05 \x01(\tR\bbuyPrice\x12\x12\n" +
	"\x04rate\x18\x06 \x01(\tR\x04rate\x12#\n" +
	"\rhours24_trade\x18\a \x01(\tR\fhours24Trade\"l\n" +
	"\x14SupportSymbolListReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"base_asset\x18\x02 \x01(\tR\tbaseAsset\x12\x1f\n" +
	"\vqoute_asset\x18\x03 \x01(\tR\n" +
	"qouteAsset\"n\n" +
	"\x14SupportSymbolListRep\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x04R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x120\n" +
	"\ftokenSymbols\x18\x03 \x03(\v2\f.TokenSymbolR\ftokenSymbols\"j\n" +
	"\x12MarketPriceListReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"base_asset\x18\x02 \x01(\tR\tbaseAsset\x12\x1f\n" +
	"\vqoute_asset\x18\x03 \x01(\tR\n" +
	"qouteAsset\"l\n" +
	"\x12MarketPriceListRep\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x04R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x120\n" +
	"\fmarketPrices\x18\x03 \x03(\v2\f.MarketPriceR\fmarketPrices2\x9e\x01\n" +
	"\x12MarketPriceService\x12F\n" +
	"\x14getSupportSymbolList\x12\x15.SupportSymbolListReq\x1a\x15.SupportSymbolListRep\"\x00\x12@\n" +
	"\x12getMarketPriceList\x12\x13.MarketPriceListReq\x1a\x13.MarketPriceListRep\"\x00B\x10Z\x0e./proto/marketb\x06proto3"

var (
	file_proto_market_proto_rawDescOnce sync.Once
	file_proto_market_proto_rawDescData []byte
)

func file_proto_market_proto_rawDescGZIP() []byte {
	file_proto_market_proto_rawDescOnce.Do(func() {
		file_proto_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_market_proto_rawDesc), len(file_proto_market_proto_rawDesc)))
	})
	return file_proto_market_proto_rawDescData
}

var file_proto_market_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_market_proto_goTypes = []any{
	(*Exchange)(nil),             // 0: Exchange
	(*TokenSymbol)(nil),          // 1: TokenSymbol
	(*MarketPrice)(nil),          // 2: MarketPrice
	(*SupportSymbolListReq)(nil), // 3: SupportSymbolListReq
	(*SupportSymbolListRep)(nil), // 4: SupportSymbolListRep
	(*MarketPriceListReq)(nil),   // 5: MarketPriceListReq
	(*MarketPriceListRep)(nil),   // 6: MarketPriceListRep
}
var file_proto_market_proto_depIdxs = []int32{
	0, // 0: TokenSymbol.exchanges:type_name -> Exchange
	1, // 1: SupportSymbolListRep.tokenSymbols:type_name -> TokenSymbol
	2, // 2: MarketPriceListRep.marketPrices:type_name -> MarketPrice
	3, // 3: MarketPriceService.getSupportSymbolList:input_type -> SupportSymbolListReq
	5, // 4: MarketPriceService.getMarketPriceList:input_type -> MarketPriceListReq
	4, // 5: MarketPriceService.getSupportSymbolList:output_type -> SupportSymbolListRep
	6, // 6: MarketPriceService.getMarketPriceList:output_type -> MarketPriceListRep
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_market_proto_init() }
func file_proto_market_proto_init() {
	if File_proto_market_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_market_proto_rawDesc), len(file_proto_market_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_market_proto_goTypes,
		DependencyIndexes: file_proto_market_proto_depIdxs,
		MessageInfos:      file_proto_market_proto_msgTypes,
	}.Build()
	File_proto_market_proto = out.File
	file_proto_market_proto_goTypes = nil
	file_proto_market_proto_depIdxs = nil
}
