// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: proto/market.proto

package market

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarketPriceService_GetSupportSymbolList_FullMethodName = "/MarketPriceService/getSupportSymbolList"
	MarketPriceService_GetMarketPriceList_FullMethodName   = "/MarketPriceService/getMarketPriceList"
)

// MarketPriceServiceClient is the client API for MarketPriceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarketPriceServiceClient interface {
	GetSupportSymbolList(ctx context.Context, in *SupportSymbolListReq, opts ...grpc.CallOption) (*SupportSymbolListRep, error)
	GetMarketPriceList(ctx context.Context, in *MarketPriceListReq, opts ...grpc.CallOption) (*MarketPriceListRep, error)
}

type marketPriceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketPriceServiceClient(cc grpc.ClientConnInterface) MarketPriceServiceClient {
	return &marketPriceServiceClient{cc}
}

func (c *marketPriceServiceClient) GetSupportSymbolList(ctx context.Context, in *SupportSymbolListReq, opts ...grpc.CallOption) (*SupportSymbolListRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SupportSymbolListRep)
	err := c.cc.Invoke(ctx, MarketPriceService_GetSupportSymbolList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketPriceServiceClient) GetMarketPriceList(ctx context.Context, in *MarketPriceListReq, opts ...grpc.CallOption) (*MarketPriceListRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarketPriceListRep)
	err := c.cc.Invoke(ctx, MarketPriceService_GetMarketPriceList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketPriceServiceServer is the server API for MarketPriceService service.
// All implementations should embed UnimplementedMarketPriceServiceServer
// for forward compatibility.
type MarketPriceServiceServer interface {
	GetSupportSymbolList(context.Context, *SupportSymbolListReq) (*SupportSymbolListRep, error)
	GetMarketPriceList(context.Context, *MarketPriceListReq) (*MarketPriceListRep, error)
}

// UnimplementedMarketPriceServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketPriceServiceServer struct{}

func (UnimplementedMarketPriceServiceServer) GetSupportSymbolList(context.Context, *SupportSymbolListReq) (*SupportSymbolListRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSupportSymbolList not implemented")
}
func (UnimplementedMarketPriceServiceServer) GetMarketPriceList(context.Context, *MarketPriceListReq) (*MarketPriceListRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarketPriceList not implemented")
}
func (UnimplementedMarketPriceServiceServer) testEmbeddedByValue() {}

// UnsafeMarketPriceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketPriceServiceServer will
// result in compilation errors.
type UnsafeMarketPriceServiceServer interface {
	mustEmbedUnimplementedMarketPriceServiceServer()
}

func RegisterMarketPriceServiceServer(s grpc.ServiceRegistrar, srv MarketPriceServiceServer) {
	// If the following call pancis, it indicates UnimplementedMarketPriceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarketPriceService_ServiceDesc, srv)
}

func _MarketPriceService_GetSupportSymbolList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupportSymbolListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketPriceServiceServer).GetSupportSymbolList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketPriceService_GetSupportSymbolList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketPriceServiceServer).GetSupportSymbolList(ctx, req.(*SupportSymbolListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketPriceService_GetMarketPriceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarketPriceListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketPriceServiceServer).GetMarketPriceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketPriceService_GetMarketPriceList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketPriceServiceServer).GetMarketPriceList(ctx, req.(*MarketPriceListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MarketPriceService_ServiceDesc is the grpc.ServiceDesc for MarketPriceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketPriceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MarketPriceService",
	HandlerType: (*MarketPriceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getSupportSymbolList",
			Handler:    _MarketPriceService_GetSupportSymbolList_Handler,
		},
		{
			MethodName: "getMarketPriceList",
			Handler:    _MarketPriceService_GetMarketPriceList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/market.proto",
}
