// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: protobuf/wallet.proto

package wallet

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WalletService_GetChainMethod_FullMethodName                       = "/kanthub.wallet.WalletService/getChainMethod"
	WalletService_GetChainSchema_FullMethodName                       = "/kanthub.wallet.WalletService/getChainSchema"
	WalletService_CreateKeyPairsAndExportPublicKeyList_FullMethodName = "/kanthub.wallet.WalletService/createKeyPairsAndExportPublicKeyList"
	WalletService_CreatKeyPairsWithAddresses_FullMethodName           = "/kanthub.wallet.WalletService/creatKeyPairsWithAddresses"
	WalletService_BuildAndSignTransaction_FullMethodName              = "/kanthub.wallet.WalletService/buildAndSignTransaction"
	WalletService_BuildAndSignBatchTransaction_FullMethodName         = "/kanthub.wallet.WalletService/buildAndSignBatchTransaction"
)

// WalletServiceClient is the client API for WalletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WalletServiceClient interface {
	GetChainMethod(ctx context.Context, in *ChainSignMethodRequest, opts ...grpc.CallOption) (*ChainSignMethodResponse, error)
	GetChainSchema(ctx context.Context, in *ChainSchemaRequest, opts ...grpc.CallOption) (*ChainSchemaResponse, error)
	CreateKeyPairsAndExportPublicKeyList(ctx context.Context, in *CreateKeyPairAndExportPublicKeyRequest, opts ...grpc.CallOption) (*CreateKeyPairAndExportPublicKeyResponse, error)
	CreatKeyPairsWithAddresses(ctx context.Context, in *CreatKeyPairsWithAddressesRequest, opts ...grpc.CallOption) (*CreatKeyPairsWithAddressesResponse, error)
	BuildAndSignTransaction(ctx context.Context, in *BuildAndSignTransactionRequest, opts ...grpc.CallOption) (*BuildAndSignTransactionResponse, error)
	BuildAndSignBatchTransaction(ctx context.Context, in *BuildAndSignBatchTransactionRequest, opts ...grpc.CallOption) (*BuildAndSignTransactionResponse, error)
}

type walletServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletServiceClient(cc grpc.ClientConnInterface) WalletServiceClient {
	return &walletServiceClient{cc}
}

func (c *walletServiceClient) GetChainMethod(ctx context.Context, in *ChainSignMethodRequest, opts ...grpc.CallOption) (*ChainSignMethodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChainSignMethodResponse)
	err := c.cc.Invoke(ctx, WalletService_GetChainMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetChainSchema(ctx context.Context, in *ChainSchemaRequest, opts ...grpc.CallOption) (*ChainSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChainSchemaResponse)
	err := c.cc.Invoke(ctx, WalletService_GetChainSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) CreateKeyPairsAndExportPublicKeyList(ctx context.Context, in *CreateKeyPairAndExportPublicKeyRequest, opts ...grpc.CallOption) (*CreateKeyPairAndExportPublicKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateKeyPairAndExportPublicKeyResponse)
	err := c.cc.Invoke(ctx, WalletService_CreateKeyPairsAndExportPublicKeyList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) CreatKeyPairsWithAddresses(ctx context.Context, in *CreatKeyPairsWithAddressesRequest, opts ...grpc.CallOption) (*CreatKeyPairsWithAddressesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatKeyPairsWithAddressesResponse)
	err := c.cc.Invoke(ctx, WalletService_CreatKeyPairsWithAddresses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) BuildAndSignTransaction(ctx context.Context, in *BuildAndSignTransactionRequest, opts ...grpc.CallOption) (*BuildAndSignTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildAndSignTransactionResponse)
	err := c.cc.Invoke(ctx, WalletService_BuildAndSignTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) BuildAndSignBatchTransaction(ctx context.Context, in *BuildAndSignBatchTransactionRequest, opts ...grpc.CallOption) (*BuildAndSignTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildAndSignTransactionResponse)
	err := c.cc.Invoke(ctx, WalletService_BuildAndSignBatchTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServiceServer is the server API for WalletService service.
// All implementations should embed UnimplementedWalletServiceServer
// for forward compatibility.
type WalletServiceServer interface {
	GetChainMethod(context.Context, *ChainSignMethodRequest) (*ChainSignMethodResponse, error)
	GetChainSchema(context.Context, *ChainSchemaRequest) (*ChainSchemaResponse, error)
	CreateKeyPairsAndExportPublicKeyList(context.Context, *CreateKeyPairAndExportPublicKeyRequest) (*CreateKeyPairAndExportPublicKeyResponse, error)
	CreatKeyPairsWithAddresses(context.Context, *CreatKeyPairsWithAddressesRequest) (*CreatKeyPairsWithAddressesResponse, error)
	BuildAndSignTransaction(context.Context, *BuildAndSignTransactionRequest) (*BuildAndSignTransactionResponse, error)
	BuildAndSignBatchTransaction(context.Context, *BuildAndSignBatchTransactionRequest) (*BuildAndSignTransactionResponse, error)
}

// UnimplementedWalletServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWalletServiceServer struct{}

func (UnimplementedWalletServiceServer) GetChainMethod(context.Context, *ChainSignMethodRequest) (*ChainSignMethodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChainMethod not implemented")
}
func (UnimplementedWalletServiceServer) GetChainSchema(context.Context, *ChainSchemaRequest) (*ChainSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChainSchema not implemented")
}
func (UnimplementedWalletServiceServer) CreateKeyPairsAndExportPublicKeyList(context.Context, *CreateKeyPairAndExportPublicKeyRequest) (*CreateKeyPairAndExportPublicKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateKeyPairsAndExportPublicKeyList not implemented")
}
func (UnimplementedWalletServiceServer) CreatKeyPairsWithAddresses(context.Context, *CreatKeyPairsWithAddressesRequest) (*CreatKeyPairsWithAddressesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatKeyPairsWithAddresses not implemented")
}
func (UnimplementedWalletServiceServer) BuildAndSignTransaction(context.Context, *BuildAndSignTransactionRequest) (*BuildAndSignTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuildAndSignTransaction not implemented")
}
func (UnimplementedWalletServiceServer) BuildAndSignBatchTransaction(context.Context, *BuildAndSignBatchTransactionRequest) (*BuildAndSignTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuildAndSignBatchTransaction not implemented")
}
func (UnimplementedWalletServiceServer) testEmbeddedByValue() {}

// UnsafeWalletServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletServiceServer will
// result in compilation errors.
type UnsafeWalletServiceServer interface {
	mustEmbedUnimplementedWalletServiceServer()
}

func RegisterWalletServiceServer(s grpc.ServiceRegistrar, srv WalletServiceServer) {
	// If the following call pancis, it indicates UnimplementedWalletServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WalletService_ServiceDesc, srv)
}

func _WalletService_GetChainMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChainSignMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetChainMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_GetChainMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetChainMethod(ctx, req.(*ChainSignMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetChainSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChainSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetChainSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_GetChainSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetChainSchema(ctx, req.(*ChainSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_CreateKeyPairsAndExportPublicKeyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKeyPairAndExportPublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).CreateKeyPairsAndExportPublicKeyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_CreateKeyPairsAndExportPublicKeyList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).CreateKeyPairsAndExportPublicKeyList(ctx, req.(*CreateKeyPairAndExportPublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_CreatKeyPairsWithAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatKeyPairsWithAddressesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).CreatKeyPairsWithAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_CreatKeyPairsWithAddresses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).CreatKeyPairsWithAddresses(ctx, req.(*CreatKeyPairsWithAddressesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_BuildAndSignTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildAndSignTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).BuildAndSignTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_BuildAndSignTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).BuildAndSignTransaction(ctx, req.(*BuildAndSignTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_BuildAndSignBatchTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildAndSignBatchTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).BuildAndSignBatchTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_BuildAndSignBatchTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).BuildAndSignBatchTransaction(ctx, req.(*BuildAndSignBatchTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WalletService_ServiceDesc is the grpc.ServiceDesc for WalletService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalletService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kanthub.wallet.WalletService",
	HandlerType: (*WalletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getChainMethod",
			Handler:    _WalletService_GetChainMethod_Handler,
		},
		{
			MethodName: "getChainSchema",
			Handler:    _WalletService_GetChainSchema_Handler,
		},
		{
			MethodName: "createKeyPairsAndExportPublicKeyList",
			Handler:    _WalletService_CreateKeyPairsAndExportPublicKeyList_Handler,
		},
		{
			MethodName: "creatKeyPairsWithAddresses",
			Handler:    _WalletService_CreatKeyPairsWithAddresses_Handler,
		},
		{
			MethodName: "buildAndSignTransaction",
			Handler:    _WalletService_BuildAndSignTransaction_Handler,
		},
		{
			MethodName: "buildAndSignBatchTransaction",
			Handler:    _WalletService_BuildAndSignBatchTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/wallet.proto",
}
